### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by ramzialhaddad** [weespin/WillFromAfarDownloader#10]
I think I would personally use this wayy more if there was a command line version of it.

**Comment by weespin** [comment]
It's possible to run requestify in CLI mode
(https://ci.appveyor.com/project/weespin26279/requestifytf2/build/artifacts
,  download Release\RequesifyCLI.exe and drop into normal requestify
folder), however I don't remember commands (you can type /help or help in
console to get possible commands)

**Comment by ramzialhaddad** [comment]
Right but this doesn't really solve my issue since I can't access the actual audio downloader.

**Comment by TheWaterHippo** [comment]
Okay. I have literally no reason why I decided to do this, but here you go. A CLI version of this project.
https://github.com/TheWaterHippo/WillFromAfarDownloader

**Comment by ramzialhaddad** [comment]
> 
> 
> Okay. I have literally no reason why I decided to do this, but here you go. A CLI version of this project.
> https://github.com/TheWaterHippo/WillFromAfarDownloader

Damn good work, though I can't seem to compile it with my computer. Can you make a build on your fork?

**Comment by TheWaterHippo** [comment]
That's a bit odd. Are you building the solution as a whole or just compiling the UI? Did you also download the required libraries? This one uses System.Commandline library to make it CLI. I'll see if I can make a build soon.

**Comment by ramzialhaddad** [comment]
Likely its just me not knowing how to use visual studio very well lol

**Comment by weespin** [comment]
Added in c0dd2b2aea6c649e0da4cdaa3d687af6b1c7f0e0
