### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by theguygoopy** [weespin/WillFromAfarDownloader#12]
I have no programming knowledge but I use this program for meme-ing in games with friends but no matter how I set my options, my voice sounds normal while any TTS voice I use is ear shatteringly loud to my friends. Is there a way to change the volume output without changing my global volume settings? Otherwise I need to change my volume to make me sound super quiet every time I use TTS.

**Comment by weespin** [comment]
Added in c0dd2b2aea6c649e0da4cdaa3d687af6b1c7f0e0
