### ISSUE TITLE
Vocal Sound Smileys, Currently Do Not Play While Using Your Application 

### ISSUE THREAD

**Issue by queenslight** [weespin/WillFromAfarDownloader#13]
First off, 
Congrats to you on creating this fine application! I wasn't sure where to put my thanks, thus I place it here.

Secondly on to the issue:

Vocal Sound Smileys, such as #AARGH01#, #FIRE SIREN#, and  #SLEEP01#, only work while logged into the site directly. 
Words on the other hand, working as expected,perfectly!

You can find a list of all Vocal Smileys, at the link provided below. Keep up the fantastic work! 

[Acapela Group | Vocal Smileys examples ](https://www.acapela-group.com/vocal-smileys-examples/)

**Comment by weespin** [comment]
The program cannot support this, it does not use the web version of TTS

**Comment by queenslight** [comment]
Ah hah!
Thanks for the heads up on that! 
You may wish to put said Vocal Smileys link in the ReadMe document, and let folks know that only Vocal Exclamations work with your program and not the sound emotions. 

May you have a good day!
Feel free to close this ticket.
PS. A similar ticket with the word "tags" in the subject line from March of 2018, can also be closed, as it was referring to these. 
Thanks! again, for your reply.
