### ISSUE TITLE
Doesn't work with WINE on linux, a linux-compatible version would be awesome.

### ISSUE THREAD

**Issue by SunbroJedi** [weespin/WillFromAfarDownloader#16]

**Comment by weespin** [comment]
I have updated the program
You can test it on your system?
https://github.com/weespin/WillFromAfarDownloader#installation-guide-for-linux

**Comment by SunbroJedi** [comment]
Sorry I didn't respond, I've been having some other issues with other stuff and didn't see this. It still doesn't work. It launches but when I click play there's no sound.

**Comment by weespin** [comment]
Can you provide an distribution name/version?
Also try to update your Wine

**Comment by SunbroJedi** [comment]
Distribution? Arch Linux.

My wine is updated. I might actually have to downgrade it.

**Comment by weespin** [comment]
Everything is working perfectly on wine-5.0.3 (Debian 5.0.3-3)
I've updated wine to 6.6 (devel) and AcapellaDownloader is still working 
![proof](https://yiff.nullcoreproject.net/i/260bb8b7.png)
Edit: AcapellaDownloader works under wine 6.0 too
![proof2](https://yiff.nullcoreproject.net/i/a7849bc0.png)

**Comment by SunbroJedi** [comment]
Hmm, interesting. Are you sure the audio is working?

I might be actually missing some stuff because I'm using a pretty new install of arch.

I'll try again later.

**Comment by weespin** [comment]
> Are you sure the audio is working?

Yeah, all features are working.
