### ISSUE TITLE
WillFromAfarDownloader (v2.2.2) Cannot Download or Play

### ISSUE THREAD

**Issue by P0W3** [weespin/WillFromAfarDownloader#18]
In WillFromAfarDownloader (v2.2.2), I typed some words, I clicked the Download button, and it did not work. I clicked the Play button, and it did not work.

I use Windows (64-bit) (v10.0.19043.1237).

![image](https://user-images.githubusercontent.com/18279115/134878208-e8b5c410-0d75-4bf2-b79e-9b855432257d.png)
![image](https://user-images.githubusercontent.com/18279115/134878176-4eba34cb-f083-469c-911d-1a695a042ff2.png)
![image](https://user-images.githubusercontent.com/18279115/134878901-125cd62c-e740-40c6-a012-448479b828de.png)

**Comment by JohanBLU** [comment]
oh god. great, im having this problem too. did acapellabox one-up themselves? if so, we're screwed.

**Comment by weespin** [comment]
![image](https://user-images.githubusercontent.com/17180451/134969754-07f5f65b-80b7-4718-828c-cff5f732ce77.png)
Acapella broke their mobile app.
I hope they'll fix it as i'm using their private api for this program

**Comment by weespin** [comment]
Should work rn
