### ISSUE TITLE
Detected as a virus

### ISSUE THREAD

**Issue by Adamyus** [weespin/WillFromAfarDownloader#2]
It's detected as a Zpevdo.A virus. 

If i was you, i wont download this.

**Comment by weespin** [comment]
False positive, god damn you're on GitHub. Just recomplie project if you don't trust the build 😀
Also i can't really see [any detections from **non-static** and not **noname** antiviruses](https://www.virustotal.com/#/file/0a6733c281af3273ef0adc018506e7fc3ff5292cce5f15659c63a040b488aeb3/detection)
EDIT: Microsoft Defender found Zpevdo.A, its becouse i used Fody to include dll's into main exe file.

**Comment by weespin** [comment]
Fixed https://github.com/weespin/WillFromAfarDownloader/commit/e4dc7563b12cbaa62ffa701a0fc9e6ce60775e4d

**Comment by Adamyus** [comment]
yay that's what i wanted to hear !

**Comment by jmynes** [comment]
Seems to happen again:
https://www.virustotal.com/gui/file/3461e940fae39a7cdec6424476816cb80edc1cb9607cc9ae292c1a612cb78b4c/detection

**Comment by weespin** [comment]
> Seems to happen again: https://www.virustotal.com/gui/file/3461e940fae39a7cdec6424476816cb80edc1cb9607cc9ae292c1a612cb78b4c/detection

Not really. I don't care about these "static/machine learning" detections from noname antiviruses.
