### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by Funktionar** [weespin/WillFromAfarDownloader#21]
Processing speed is a bit slow. Can in the future the downloader play the message in real time(>200 ms)?

**Comment by weespin** [comment]
This is impossible since processing is done on Acapella servers.
Theoretically I can shrink loading time by ~30% by reusing nonce token

**Comment by weespin** [comment]
Optimized in https://github.com/weespin/WillFromAfarDownloader/commit/21deb72d3d1f4d40c69ca96b1ac7ca70611f1db9
