### ISSUE TITLE
text length

### ISSUE THREAD

**Issue by GandalfShallGray** [weespin/WillFromAfarDownloader#26]
You may have already fixed this issue but in the earliest version. I noticed that you can only type about 300 characters without having to delete some text. Is this still an issue or was it fixed in later versions?

**Comment by MegaBaconator** [comment]
Yes I find it very annoying. I wish there was the ability to type more characters.

**Comment by weespin** [comment]
Well, this project is emulating Acapella TTS app from the Google Store which has a server sided ~300 character limit.
I can't do anything about that.
