### ISSUE TITLE
Trojan Dowload

### ISSUE THREAD

**Issue by CSecretive** [weespin/WillFromAfarDownloader#28]
**Describe the bug**
Once i try to download the zip file im being stopped by my anti-virus. Even if i turn it off, google blocks the download.

**To Reproduce**
1. Go to 'releases'
2. Click on 'Release.zip'
3. See error

**Expected behavior**
Safe download

**Comment by weespin** [comment]
Well, try download using another browser and disable your antivirus.
Please tell which antivirus are you using. I'm really tired of these false positive detections.

**Comment by CSecretive** [comment]
> Well, try download using another browser and disable your antivirus. Please tell which antivirus are you using. I'm really tired of these false positive detections.

Kaspersky. As i found out, yes it is a false positive.
