### ISSUE TITLE
Voice ID request

### ISSUE THREAD

**Issue by Bwukki** [weespin/WillFromAfarDownloader#3]
I'm trying to add the following voices but I cannot get the IDs for them:

(us)RYAN

(us)SAUL

(uk) grahm, queenelizabeth

(jp) sakura

(ru) alyona

spanish (us) rosa

spanish (us) rodrigo

If you could add them or just find the ID so I can add them it would be awesome

**Comment by weespin** [comment]
Got voices id!
I will release them with small tool.

**Comment by weespin** [comment]
https://github.com/weespin/WillFromAfarDownloader/commit/2af9112559a0d9a0c29444a61993ca523cebaae9
Done 🙌 
I need to sleep ☠️

**Comment by Bwukki** [comment]
Thank you so much!
