### ISSUE TITLE
AcapellaDownloader error

### ISSUE THREAD

**Issue by OliveSouch** [weespin/WillFromAfarDownloader#31]
I can't make Acapela voice speak.
![Screenshot_41](https://user-images.githubusercontent.com/131188048/236246187-5cfd1b4b-c177-4102-97b3-e7fbf930d5cc.png)

**Comment by weespin** [comment]
Everything works on my and CI side
https://ci.appveyor.com/project/weespin26279/willfromafardownloader/builds/46963559

Please press the Details button and paste the log.

**Comment by OliveSouch** [comment]
Never mind, it's now fixed for me.
