### ISSUE TITLE
None of the voices generate.

### ISSUE THREAD

**Issue by thetoonsofjosh** [weespin/WillFromAfarDownloader#33]
I'm using the most recent version and all of the voices do not generate the text I wanted, but instead just generates a blank audio file, Is it just me or is anyone else having the same problem?

**Comment by Brandon100000** [comment]
SAME!!!!!!

**Comment by Kawaii123456** [comment]
I'm having that problem too! i seriously thought my volume was low, but nope, you can't hear any voices, please fix this ASAP.

**Comment by AustinTheSuperiorVyonder2021** [comment]
Version 2.3.2 still works for me.

**Comment by AustinTheSuperiorVyonder2021** [comment]
Something is wrong with the audio of the voices. Please adjust this since I can't hear them.

**Comment by weespin** [comment]
Same as https://github.com/weespin/WillFromAfarDownloader/issues/18#issuecomment-928189405

**Comment by HUXAIFAZAKI** [comment]
( I'm using the most recent version and all of the voices do not generate the text I wanted, but instead just generates a blank audio file ) Same , FIX ASAP : (

**Comment by weespin** [comment]
@FearlessOffical please look at my message above. I'll lock the conversation.

**Comment by weespin** [comment]
Fixed in https://github.com/weespin/WillFromAfarDownloader/commit/78dc6cd4bc42619fe4898c3fd4c9b1da8ee123b3
