### ISSUE TITLE
voice no longer generates

### ISSUE THREAD

**Issue by testtest954** [weespin/WillFromAfarDownloader#36]
it seems that the acapella tts were broken and cannot generate but exporting it makes it blank
so i have to wait? or is there alternative?

**Comment by masterblek93** [comment]
I think this is the end... :(

**Comment by Kawaii123456** [comment]
the API got messed with, that's why it's not working <:(

**Comment by testtest954** [comment]
why did the api got messed up?

**Comment by flasher1101** [comment]
Finally I learned how to do it for free not relying on this software. I think smart guys also did it

**Comment by masterblek93** [comment]
> Finally I learned how to do it for free not relying on this software. I think smart guys also did it

So, what did you do?

**Comment by flasher1101** [comment]
If I tell you and everyone  uses it, it will also get banned. Like this same software.

**Comment by masterblek93** [comment]
> If I tell you and everyone uses it, it will also get banned. Like this same software.

Send me a PM then.
I have no desire to ruin something that I like to use.

**Comment by Kawaii123456** [comment]
> Finally I learned how to do it for free not relying on this software. I think smart guys also did it

Can you please send me a PM on how you do this please? what do you do? i also have no desire to ruin something that I like to use. Thank you.

**Comment by WaleedAnimate2020** [comment]
> > Finally I learned how to do it for free not relying on this software. I think smart guys also did it
> 
> Can you please send me a PM on how you do this please? what do you do? i also have no desire to ruin something that I like to use. Thank you.

So do I too.

**Comment by testtest954** [comment]
> Finally I learned how to do it for free not relying on this software. I think smart guys also did it


send me a pm

**Comment by masterblek93** [comment]
> Finally I learned how to do it for free not relying on this software. I think smart guys also did it

Guys, he is trolling.
He hasn't contacted any of us.
