### ISSUE TITLE
New voices that I found on TTS Acapela app

### ISSUE THREAD

**Issue by WaleedAnimate2020** [weespin/WillFromAfarDownloader#39]
As you know, I found more voices from Acapela.

List:

Alinora (US English)
Baelara (US English)
Camryn (US English)
Darian (US English)
Darius (US English)
Eldowen (US English)
Faelena (US English)
Gilthor (US English)
Haldria (US English)
Ilion (US English)
Lizzie (US English)
Malik (US English)
Micah (US English)
Nelly (US English)
Owen (US English)
Tamira (US English)
Tiana (US English)
Amy (UK English)
Alfie (UK English)
Vidhi (Indian English)
Archie (Scottish English)
Eilidh (Scottish English)
Julian (Canadian English)
Melany (Canadian English)
Victoria (Canadian English)

Anthony (Canadian French)
Julien (Canadian French)
Melanie (Canadian French)
Victoire (Canadian French)

Vidhi (Hindi)

Piotr (Polish)

Isabel (Portuguese)
Sergia (Brazilian Portuguese)

Merel (Dutch)
Thijs (Dutch)

Rikke (Danish)

Can you add them please?

**Comment by weespin** [comment]
Hey! It's a quite large list :D
Do you have any voice links (.bvcu) for them?
If yeah, please create a pull request ❤️

**Comment by WaleedAnimate2020** [comment]
It's on Voices.cs.

new Voice("Rikke", Gender.Female, "da_dk", "dad_rikke_22k_ns.bvcu"),
 new Voice("Julian", Gender.Male, "en_CA", "en_ca_julian_22k_ns.bvcu"),
new Voice("Victoria", Gender.Female, "en_CA", "en_ca_victoria_22k_ns.bvcu"),
new Voice("Melany", Gender.Female, "en_CA", "en_ca_melany_22k_ns.bvcu"),
new Voice("Alfie", Gender.Male, "en_gb", "en_nen_alfie_22k_ns.bvcu"),
new Voice("Amy", Gender.Female, "en_gb", "en_nen_amy_22k_ns.bvcu"),
new Voice("VidhiEnglish", Gender.Female, "en_in", "en_in_vidhienglish_22k_ns.bvcu"),
new Voice("Archie", Gender.Male, "gd_GB", "en_sct_archie_22k_ns.bvcu"),
new Voice("Eilidh", Gender.Female, "gd_GB", "en_sct_eilidh_22k_ns.bvcu"),
new Voice("Malik", Gender.Male, "en_us", "enu_malik_22k_ns.bvcu"),
new Voice("Owen", Gender.Male, "en_us", "enu_owen_22k_ns.bvcu"),
new Voice("Eldowen", Gender.Male, "en_us", "enu_eldowen_22k_ns.bvcu"),
new Voice("Gilthor", Gender.Male, "en_us", "enu_gilthor_22k_ns.bvcu"),
new Voice("Ilion", Gender.Male, "en_us", "enu_ilion_22k_ns.bvcu"),
new Voice("Darius", Gender.Male, "en_us", "enu_darius_22k_ns.bvcu"),
new Voice("Tamira", Gender.Female, "en_us", "enu_tamira_22k_ns.bvcu"),
new Voice("Alinora", Gender.Female, "en_us", "enu_alinora_22k_ns.bvcu"),
new Voice("Haldria", Gender.Female, "en_us", "enu_haldria_22k_ns.bvcu"),
new Voice("Camryn", Gender.Female, "en_us", "enu_camryn_22k_ns.bvcu"),
new Voice("Baelara", Gender.Female, "en_us", "enu_baelara_22k_ns.bvcu"),
new Voice("Faelena", Gender.Female, "en_us", "enu_faelena_22k_ns.bvcu"),
new Voice("Tiana", Gender.Female, "en_us", "enu_tiana_22k_ns.bvcu"),
new Voice("Lizzie", Gender.Female, "en_us", "enu_lizzie_22k_ns.bvcu"),
new Voice("Darian", Gender.Female, "en_us", "enu_darian_22k_ns.bvcu"),
new Voice("Jorvik", Gender.Male, "en_us", "enu_jorvik_22k_ns.bvcu"),
new Voice("Anthony", Gender.Male, "fr_ca", "frc_anthony_22k_ns.bvcu"),
new Voice("Melanie", Gender.Female, "fr_ca", "frc_melanie_22k_ns.bvcu"),
new Voice("Julien", Gender.Male, "fr_ca", "frc_julien_22k_ns.bvcu"),
new Voice("Victoire", Gender.Female, "fr_ca", "frc_victoire_22k_ns.bvcu"),
new Voice("Vidhi", Gender.Female, "hi_in", "hi_in_vidhi_22k_ns.bvcu"),
new Voice("Thijs", Gender.Male, "nl_nl", "dun_thijs_22k_ns.bvcu"),
new Voice("Merel", Gender.Female, "nl_nl", "dun_merel_22k_ns.bvcu"),
new Voice("Piotr", Gender.Male, "pl_pl", "pop_piotr_22k_ns.bvcu"),
new Voice("Sergio", Gender.Male, "pt_br", "pob_sergio_22k_ns.bvcu"),
new Voice("Isabel", Gender.Female, "pt_pt", "poe_isabel_22k_ns.bvcu"),

Unfortunately for Jorvik. I can hear a small noise when I generate his voice. Can you fix that?

**Comment by ghost** [comment]
Ummmmm 
![Screenshot 2024-07-01 212801](https://github.com/weespin/WillFromAfarDownloader/assets/156873110/8a052ebc-94cb-4a18-8035-13e0d5eecc1f)

**Comment by Kawaii123456** [comment]
> Ummmmm ![Screenshot 2024-07-01 212801](https://private-user-images.githubusercontent.com/156873110/344846175-8a052ebc-94cb-4a18-8035-13e0d5eecc1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTM5NTYsIm5iZiI6MTcxOTg5MzY1NiwicGF0aCI6Ii8xNTY4NzMxMTAvMzQ0ODQ2MTc1LThhMDUyZWJjLTk0Y2ItNGExOC04MDM1LTEzZTBkNWVlY2MxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMlQwNDE0MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGI3ZTg4ZDRiNjEyODRlNjFlMTk0YTM3Mzc2NWMwMGIyN2U0YTU1MzdjMzBmN2NmNWY5OGFkZTFhYzAwMDA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tB1UmiDJAO68kizxcCojAp475PPTUzh-zCD5-QbQ_Vo)

Believe me, it's happened to me also, i thought it was my end at first, Now i see it's happening with everyone else O.O

**Comment by Trashycount** [comment]
Is there any install requirements to use this? im also getting that unhandled exception even after redownloading

**Comment by weespin** [comment]
On hold till Acapela fixes their mobile app endpoint

**Comment by levi-creator-max** [comment]
Waleed, add Child voices again and fix Jorvik and Haldria EXCLA please! I beg you! I really want to do the AI Magic School Bus audiobooks

**Comment by Brandon886673** [comment]
Can you add the Polish children's voices please? Can you add Taylor, Gosia, Zeynep, Lily, Nizareng, Sophia, Anke, Jalal, Ida, Christina, Ana, Elena, Lena, Gabriela, Tessa, Christina, Constance, and Heather please?  Can you fix the Jorvik voice and US EXCLA Haldria? Thanks!

**Comment by levi-creator-max** [comment]
And make sure you get Darian in Acapela TTS Android app! Thank you!

**Comment by levi-creator-max** [comment]
And Polish children's voices too! Thank you!

**Comment by Brandon886673** [comment]
and Emilie is in the wrong pitch and in the wrong speed.

**Comment by mikey303** [comment]
Just wanted to say thank you for sharing these!

**Comment by weespin** [comment]
A bit of clarification here:

@levi-creator-max:
I've never made an Android app for Acapela TTS. Acapela made it, and it's their official app which I've 'hacked' to learn how to use their internal protocols. 
While their Android app is no longer active, the original WillFromAfarDownloader is also not functional (for now, I hope), because it relies on Android app servers which are down at the moment.

About Type And Talk Edition (the recent release):
It uses Acapela's web demo, which you can find at [Acapela Group](https://www.acapela-group.com/demos/), but without background noise (thanks to their inadequate API). I can't add old voices back for now as long as the Acapela TTS Android app remains inactive.

**Comment by levi-creator-max** [comment]
I know, but Acapela Group made it, so ask Acapela Group and contact them to add Darian to Android Acapela TTS Voices and fix Jorvik voice so he can be heard and EXCla Haldria to be fixed, Polish Children Voices! And put those child voices back together in Acapela.EXE! If not, do you know who's great at it?

**Comment by levi-creator-max** [comment]
Oh and Waleed, can you tell Acapela Group workers to get Lily, Taylor, Nizareng, Gosia, Lena, Sophia, Ana, Darian, Elena, Christina, Heather, Constance, Jalal, Ida, Zeynep, Gabriela, Tessa, Barbara, and Anke and Polish Child voices on Acapela TTS Andrioid app!

**Comment by weespin** [comment]
@levi-creator-max
I'm kindly asking you to stop spamming these threads.
>Can you tell Acapela Group workers

No, but you can always buy their offline voices for Android/Web apps. They should work without this program.
And please DO NOT contact Acapela. It’s unthinkable to inform them that their actions have caused my "hack," which allows using their product for free, to stop working. 🤦

**Comment by weespin** [comment]
Closed due to Acapela's api changing. 
Only the tap and talk edition works
