### ISSUE TITLE
Unable to connect to Remote Server

### ISSUE THREAD

**Issue by BartoszMikMik** [weespin/WillFromAfarDownloader#40]
Whenever I try using WillfromAfarDownloader the Error message saying "Unable to connect to remote Server" appears.

**To Reproduce**
1. Try and Play or Download Given Spoken Text.
2. See error.

**Expected behavior**
For it to work

![image](https://github.com/weespin/WillFromAfarDownloader/assets/174744610/a044c00f-29a6-4055-916e-938d99cd3a8f)

I dont know if this is an issue due to some recent pc update or what, but it confuses me since this is even happening to me on the latest version

**Comment by 6njxm3** [comment]
The same thing is happening to me, it's weird.

**Comment by WaleedAnimate2020** [comment]
Same goes with me! When will it fixed soon?

**Comment by 6njxm3** [comment]
I have no idea, but hopefully soon I NEED SAUL!

**Comment by glitchxp** [comment]
same issue here, really odd. maybe its because of acapella's closure?

**Comment by 6njxm3** [comment]
> Same goes with me! When will it fixed soon?

Wait a damn second, YOUR THE DEVOLOPER!

**Comment by WaleedAnimate2020** [comment]
> same issue here, really odd. maybe its because of acapella's closure?

I'm afraid so! I'm really sorry about that

**Comment by 6njxm3** [comment]
> > same issue here, really odd. maybe its because of acapella's closure?
> 
> I'm afraid so! I'm really sorry about that

We still have infovox3, but im having trouble exporting mp3s

**Comment by weespin** [comment]
Hey @WaleedAnimate2020, can you try Acapela TTS Voices app on Play Market. Does it work?
https://play.google.com/store/apps/details?id=com.acapelagroup.android.tts&hl=en&pli=1

**Comment by weespin** [comment]
Good news, the fix is coming, but it will take some time.
UDP: 
And the bad things happened: The default synthesizer endpoint has died, so all voices like WillFromAfar are unavailable.
I'm waiting for the Acapela to fix their app (for the fourth time, uhh).

I will push a small "Type&Talk" edition aka (https://www.acapela-group.com 's new online demo but without background noise)

**Comment by weespin** [comment]
I've pushed the Type And Talk Edition.
Sadly, it doesn't contain usual voices like (WillFromAfar)
https://github.com/weespin/WillFromAfarDownloader/releases/tag/2.4.2

**Comment by WaleedAnimate2020** [comment]
are children voices are available too beside adult ones?

**Comment by WaleedAnimate2020** [comment]
> Hey @WaleedAnimate2020, can you try Acapela TTS Voices app on Play Market. Does it work? https://play.google.com/store/apps/details?id=com.acapelagroup.android.tts&hl=en&pli=1

The voices are still don't work anymore. I'm really sorry

**Comment by levi-creator-max** [comment]
Hey guys! And Waleed, I want to fix Haldria EXCLA, fix Jorvik voice, and add Acapela TTS Voices to it! Because I want them to be completely done! Or we won't have access to Acapela TTS Exe anyone!

**Comment by levi-creator-max** [comment]
And can you add Child voices again too?

**Comment by levi-creator-max** [comment]
Hey, Waleed! I just got a comment from BabyEinsteinLover at Deviantart that we need you to add Child voices again! Ella, Josh, Emilio, Valeria, Scott, Lizzie, Malik, Owen, Tiana, Alinora, Baelara, Camryn, Darian, Eldowen, Faelena, Gilthor, Haldria but her EXCLA needs to be fixed, Ilion, Jorvik which needs to be fixed too, Liam, Olivia, Harry, Rosie, Alfie, Amy, Archie, Eilidh, Julian and Victoria! Please will you do it for Acapela Group? I want Darian to be in the Acapela TTS App on Google Play Android too! So ask them to add Darian to Android Acapela TTS and put child voices again (but only if Haldria's EXCLA and Jorvik is fixed in time)

**Comment by levi-creator-max** [comment]
Waleed! Me and BabyEinsteinLover from Deviantart need you to fix Acapela downloader exe, fix Jorvik and make him heard, fix EXCLA Haldria, put those child voices back together, and put Polish Child's voices! Please! Do it! Or I'll be upset and we don't have what we need!

**Comment by thetoonsofjosh** [comment]
so, a update for the Acapela TTS Voices app on Android 2 days ago doesn't let you to type the voices whatever you want to say, but rather only plays a preview of said voice, possibly removed?

Guess it is, while the voices do function, they aren't actually apart of the api, rather, they are wav files inside the apk itself.

**Comment by thetoonsofjosh** [comment]
> so, a update for the Acapela TTS Voices app on Android 2 days ago doesn't let you to type the voices whatever you want to say, but rather only plays a preview of said voice, possibly removed?

After some thinking, I don't think this is the case, the voice still function and even still say "Why not try me out with our your words?", But I'm using HTTP Toolkit and I can't think where the requests are for when I make the voices speak their default lines.

**Comment by weespin** [comment]
@thetoonsofjosh 
Oh yeah, they've removed the preview feature from android version and packed the wav inside the apk file itself.
So, they've fixed their Android app, so for now the only tap and talk edition works properly.
Closing this issue
