### ISSUE TITLE
False positive on VirusTotal, explanation why?

### ISSUE THREAD

**Issue by glitchxp** [weespin/WillFromAfarDownloader#41]
I scan almost all programs I download with VirusTotal. It has helped a lot. However, I have an issue with a false positive for the program. Bvak Pro and MaxSecure, as well as a sandbox tagged this as malicious. Bvak Pro gave W32.AIDetectMalware, while MaxSecure gave Trojan.Malware.300983.susgen. Is there a specific part of the code that triggers it? Is it because it's not signatured? I have heard these _usually_ give false positives on VirusTotal. I have barely any coder knowledge. I am a beginner and go here for programs, so this is a question of mine.

I'm new to GitHub, sorry if this may have not been the best way to ask.
Thanks!

**Comment by weespin** [comment]
> Is it because it's not signatured

Yep, and the certificate to sign programs costs money.
