### ISSUE TITLE
i found an ai voice that is an archive of the old willfromafar voice

### ISSUE THREAD

**Issue by aidancarwash** [weespin/WillFromAfarDownloader#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aidancarwash** [comment]
https://www.vocalize.fm/voices/16166

**Comment by aidancarwash** [comment]
i don't know if it can be used as it requires tokens to run but it is a possible solution

**Comment by levi-creator-max** [comment]
But what about the other voices languages and child voices?

**Comment by aidancarwash** [comment]
it is the only one i have found so far I will update when i find more

**Comment by levi-creator-max** [comment]
OK! And also, when will the Acapela TTS App allow to have a preview again so it can work, and the exe too

**Comment by weespin** [comment]
It's called RVC, I've already explained about that here
https://github.com/weespin/WillFromAfarDownloader/issues/43#issuecomment-2261167557
You can do it free if you train the model by yourself, it's easy.
There's no need to use paid third party websites for that.
Closed
