### ISSUE TITLE
Character Counter/Bypassing character limit

### ISSUE THREAD

**Issue by Bwukki** [weespin/WillFromAfarDownloader#6]
If you try to send more than 300 characters, you get back "you are not allowed to process text more than 300 characters"

It would be nice to have a character counter for textBox1 so you can see if your message is too long before you hit play

Or, maybe it's possible to split a message that's longer than 300 characters into two+, then play them back to back

**Comment by weespin** [comment]
Added character limit
P.S. Its actually 350, not 300 xD
